# Generated by Django 3.0.4 on 2021-03-11 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=250)),
                ('previous_price', models.DecimalField(decimal_places=4, max_digits=10)),
                ('display_price', models.DecimalField(decimal_places=4, max_digits=10)),
                ('is_out_of_stock', models.BooleanField()),
                ('is_active', models.BooleanField(default=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'products',
                'db_table': 'product',
                'ordering': ['id'],
            },
        ),
    ]
