# Generated by Django 3.0.4 on 2021-03-27 11:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('walmart', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProductAlert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('alert_price', models.DecimalField(decimal_places=4, max_digits=10)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'user_product_alert',
                'db_table': 'user_product_alert',
                'ordering': ['id'],
            },
        ),
        migrations.AddConstraint(
            model_name='userproductalert',
            constraint=models.UniqueConstraint(fields=('product_id', 'user'), name='unique alert combo'),
        ),
    ]
